config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
 	get 'reviews/create'

  	devise_for :users
  	resources :movies
	root 'movies#index'

	get 'movies/:id/reviews' => 'reviews#create'



	namespace :admin do
		resources :users do
			put :upgrade#, on: :member # without on: :member, it should be :user_id
			put :downgrade#, on: :member
		end
	end
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, Movie
      else
        can :read, Movie
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	  mount_uploader :photo_url, PhotoUploader
	  belongs_to :user
	  has_many :reviews
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :photo, PtUploader
  	belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :posts
	has_many :reviews
	devise :database_authenticatable, :registerable,
	         :recoverable, :rememberable, :trackable, :validatable
#role may be regarded as a member variable
	def admin?
		role=="admin"? true:false
	end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController #admin - namespace
	before_action :check_admin
	layout 'admin'


	private
		def check_admin
			unless user_signed_in? && current_user.admin?
				redirect_to root_path, alert: "Should login as admin"
			end 
		end 

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
	def index
		@users = User.all
	end


	def destroy
		User.find(params[:id]).destroy 
		redirect_to admin_users_path
	end

	def upgrade
		@user=User.find(params[:user_id]) #since customized, :id -> :user_id
		@user.update(
			role: "admin"
		)
		redirect_to admin_users_path
	end 

	def downgrade
		@user=User.find(params[:user_id])
		@user.update(
			role: "regular"
		)
		redirect_to admin_users_path
	end 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  #before_action :check_admin, only: [:edit, :update, :destroy] #commented since cancancan gem is utilized
  load_and_authorize_resource
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    #authorize! :read, Movie
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
      @sum=0.0
      @movie.reviews.each {|review| @sum+=review.rating }
      @avg= @sum/(@movie.reviews.size)
    #authorize! :read, Movie
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    #authorize! :create, Movie
  end

  # GET /movies/1/edit
  def edit
    #authorize! :update, Movie
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
    #authorize! :create, Movie
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
    #authorize! :update, Movie
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
    #authorize! :destroy, Movie
  end

  private
    def check_admin
      unless current_user.admin?
        redirect_to root_path
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :desc, :photo_url)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :photo, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
  		Review.create(
  			movie_id: params[:id],
  			rating: params[:rating],
  			comment: params[:comment],
  			user_id: current_user.id
  		)
  		redirect_to movie_path(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/users/index.erb
 <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
 	<h1>User management page</h1>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>

				<% @users.each do |user| %>
	                <tr>
	                	<td><%=user.id %></td>
	                  	<td><%=user.email %></td>
	                  	<td><%=user.role %></td>
	                  	<td><%=link_to '[x]', admin_user_path(user), method:"delete", data: {confirm: "Really?"} %></td>
	                  	<td><% if user.role == "admin" %>
							<%=link_to '[Downgrade]', admin_user_downgrade_path(user), method: :put %>
						<% else %>
							<%=link_to '[Upgrade]', admin_user_upgrade_path(user), method: :put, data: {confirm: "Really??"} %>
						<% end %></td>
	                </tr>
                <% end %>
              </tbody>

            </table>
          </div>
        </main>

app/views/layouts/_admin_header.erb
 <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/admin/users">Admin page</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Settings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Help</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>

app/views/layouts/_admin_menu.erb
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#">Overview <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">User Management</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Board Management</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Statistics</a>
            </li>
          </ul>

        </nav>

       

app/views/layouts/_footer.erb
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>BK International &copy; Movies, Ratings</p>
       
      </div>
    </footer>

app/views/layouts/_header.erb
<h1 class="jumbotron-heading">Watcha Fake Webpage</h1>

<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar w/ text</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
       <%= link_to 'Home', root_path, :class=>"nav-link" %>
      </li>  
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'log_out', destroy_user_session_path, method: :delete, :class=>"nav-link" %>
        <% else %>
          <%= link_to 'log_in', new_user_session_path, :class=>"nav-link" %>
        <% end %>
          
      </li>
       <li class="nav-item ">
       <%= link_to 'admin_page', admin_users_path, :class=>"nav-link"%>
      </li>
    </ul>
    <span class="navbar-text">
      Navbar text with an inline element
    </span>
  </div>
</nav>

app/views/layouts/admin.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watcha : Movie Rating Service</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/admin_header' %>
    <div class="container-fluid">
    <div class="row">
    <%= render 'layouts/admin_menu' %>


    <div class="container">
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    </div>
    </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watcha : Movie Rating Service</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to 'log_out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'log_in', new_user_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.hidden_field :user_id, id: :user_id, value:current_user.id %>
  </div>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc, id: :movie_desc %>
  </div>


  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo_url, id: :movie_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
    <main role="main">
      <div class="album text-muted">
        <div class="container">
          <div class="row">
          <% @movies.each do |movie| %>
               <div class="card col-4" style="width: 15rem;">
                <a href="/movies/<%=movie.id%>">
                  <img class="card-img-top" src="<%=movie.photo_url%>" alt="Card image cap">
                </a>

                <div class="card-body">
                  <p class="card-text"><h5><%= movie.title %></h5></p>
                  <%= movie.reviews.first.comment unless movie.reviews.first.nil? %><br/>
                  <%= link_to 'Show', movie %>
                  <% if current_user.admin? || current_user.id == movie.user_id %>
                  <%= link_to 'Edit', edit_movie_path(movie) %>
                  <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
                </div>
              </div>
          <% end %>
          </div>
      </div>
    </div>

    </main>
    <%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
    <strong>Desc:</strong>
    <%= @movie.desc %>
</p>

<p>
    <img src="<%=@movie.photo_url%>" width="100">
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %>
<%= link_to 'Back', movies_path %>



<%= form_tag("/movies/#{@movie.id}/reviews", method: :get) do %>
<p>
    <strong>Ratings:</strong>
	1   <%=radio_button_tag(:rating,"1") %>
    2 	<%=radio_button_tag(:rating,"2") %>
    3 	<%=radio_button_tag(:rating,"3") %>
    4 	<%=radio_button_tag(:rating,"4") %>
    5 	<%=radio_button_tag(:rating,"5") %>
</p>
	<%=text_field_tag(:comment) %>
	<%=submit_tag("Submit")%>
<% end %>

 <% @movie.reviews.each do |review| %>
 <p> 
 	User : <%=review.user_id%>
 	Ratings: <%=review.rating%>
 	Comment: <%=review.comment%>
 </p>
 <% end %>

 	Rating Avg : <%=@avg%>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :post_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Photo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.photo %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @post.photo %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>